[[questions]]
question = "sample question 1"
codeSnippet = """printf(1+2);
    printf("Hello World!");"""
choices = ["A", "B", "C"]
answer =["C"]
hint = "some explanation"

[[questions]]
question = "sample question new"
choices = ["A1", "B1", "C1"]
answer = ["C1", "A1"]
hint = "some explanation for answer"

[[questions]]
question = "sample question 3"
choices = ["A1", "B1", "three"]
answer = ["three"]
hint = "some explanation for answer"