[[questions]]

prompt = "What is the purpose of using an array to store grades in the scenario mentioned at the beginning of the material?"

answer = [3]

distractors = [
    "To easily access and initialize different elements.",
    "To avoid the trouble of dealing with multiple variables.",
    "To calculate the average grade more efficiently.",
    "All of the above."
]

explainations = [
    "A, B and C are all correct. Arrays are used to store multiple values of the same type in a single variable. This makes it easier to access and initialize different elements.",
    "A, B and C are all correct. Arrays are used to store multiple values of the same type in a single variable. This makes it easier to access and initialize different elements.",
    "A, B and C are all correct. Arrays are used to store multiple values of the same type in a single variable. This makes it easier to access and initialize different elements.",
    "A, B and C are all correct. Arrays are used to store multiple values of the same type in a single variable. This makes it easier to access and initialize different elements."
]

[[questions]]

prompt = "In C programming language, how do you access the last element of an array?"

answer = [2]

distractors = [
    "By using an index of -1.",
    "By using an index of 0.",
    "By using an index one less than the size of the array.",
    "By using an index equal to the size of the array."
]

explainations = [
    "A is incorrect. In C programming language, to access the first element, we use an index of 0, which makes the last element has an index of one less than the size.",
    "B is incorrect. In C programming language, to access the first element, we use an index of 0, which makes the last element has an index of one less than the size.",
    "C is correct. In C programming language, to access the first element, we use an index of 0, which makes the last element has an index of one less than the size.",
    "D is incorrect. In C programming language, to access the first element, we use an index of 0, which makes the last element has an index of one less than the size."
]

[[questions]]

prompt = "Which of the following code can initialize an array of 5 intergers?"

answer = [1, 3]

distractors = [
'''
```
int arr[5] = {1, 2, 3};
```
''',
'''
```
int arr[5] = {1, 2, 3, 4, 5};
```
''',
'''
int arr[5];
for (int i = 1; i <= 5; i++) {
    arr[i] = i;
}
''',
'''
int arr[] = {1, 2, 3, 4, 5};
'''
]

explainations = [
    "A is correct. This is equivalent to `int arr[5] = {1, 2, 0, 0, 0};`, which means that the remaining elements in the array will be set to 0 when initializing fewer elements than the size of the array.",
    "B is correct. In C programming language, to initialize an array, we can use curly brackets to enclose the values.",
    "C is incorrect. The for loop will cause an error when `i == 5` because the index of an array starts from 0.",
    "D is correct. The compiler will deduce the size of the array from the number of element you are initializing between curly brackets."
]

[[questions]]

prompt = '''
Jade is writing a similar program to the one mentioned in the material which reverses the elements in an array. The following code expects to print out `8 9 12 2 5 7`. How many errors are there in the code?
```
#include <stdio.h>
#define SIZE 6

int main(void){
    int arr[SIZE] = [2, 5, 7, 8, 9, 12];
    for(int low = 0, high = SIZE / 2 + 1; high < SIZE; low++, high++){
        int temp = arr[low];
        arr[low] = arr[high];
        arr[high] = temp; 
    }

    for (int index = 0; index < SIZE; index++){
        printf("%d ", arr[index]);
    } 
    printf("\n");
    return 0;
}
```
'''

answer = [1]

distractors = [
    "1",
    "2",
    "3",
    "4"
]

explainations = [
'''
A is incorrect. There are 2 errors in the code.
Error 1:
At 5th line, the initialization of the array is incorrect. The correct way to initialize an array is to use curly brackets to enclose the values.

Error 2:
At 6th line, the initialization of the variable `high` is incorrect. The correct way to initialize the variable is to use `SIZE / 2` instead of `SIZE / 2 + 1`.
''',
'''
B is correct. There are 2 errors in the code.
Error 1:
At 5th line, the initialization of the array is incorrect. The correct way to initialize an array is to use curly brackets to enclose the values.

Error 2:
At 6th line, the initialization of the variable `high` is incorrect. The correct way to initialize the variable is to use `SIZE / 2` instead of `SIZE / 2 + 1`.
''',
'''
C is incorrect. There are 2 errors in the code.
Error 1:
At 5th line, the initialization of the array is incorrect. The correct way to initialize an array is to use curly brackets to enclose the values.

Error 2:
At 6th line, the initialization of the variable `high` is incorrect. The correct way to initialize the variable is to use `SIZE / 2` instead of `SIZE / 2 + 1`.
''',
'''
D is incorrect. There are 2 errors in the code.
Error 1:
At 5th line, the initialization of the array is incorrect. The correct way to initialize an array is to use curly brackets to enclose the values.

Error 2:
At 6th line, the initialization of the variable `high` is incorrect. The correct way to initialize the variable is to use `SIZE / 2` instead of `SIZE / 2 + 1`.
'''
]