[question-0]

prompt = "Jade is a beginner programmer working on a project in an Integrated Development Environment (IDE). She has just finished writing her program and wants to proceed to the next step. Which of the following should Jade do next?"

answer = [1]

distractors = ["Run the program", "Compile the program", "Test the program extensively", "Debug the program"]

explainations = [
    "Wrong. Running the program comes after compiling it. Once the code is compiled successfully, Jade can execute the program to observe its behavior and functionality.",
    "Correct. After Jade has written her program in the IDE, the next step in the development cycle is to compile the program using a compiler like GCC. Compiling the program converts the human-readable code into a machine-readable format that can be executed by the computer. This step is crucial to ensure the code is translated correctly and can be understood by the computer's hardware.",
    "Wrong. Test the program extensively: While testing is an important part of the development cycle, it typically comes after the compilation stage. Testing helps ensure the program functions correctly and meets the desired requirements.",
    "Wrong. Debug the program: Debugging is the process of finding and fixing errors or bugs in the code. While debugging is an essential step, it usually occurs after running or testing the program, as it involves identifying issues and resolving them to improve the program's functionality."
]

[question-1]

prompt = "Jade has successfully completed the development cycle for her program, and it is now working as intended. However, she wants to ensure that her code is maintainable and reusable. Which of the following actions should Jade take to achieve this?"

answer = [1]

distractors = ["Test the program extensively", "Clean the code for readability", "Re-run the program with different test cases", "Refactor the code to improve performance"]

explainations = [
    "Wrong. Testing is crucial to ensure the program functions correctly, but it primarily focuses on validating the program's functionality rather than code maintainability.",
    "To make the code maintainable and reusable, Jade should focus on cleaning the code for readability. Clean code follows best practices and standards, making it easier to understand, modify, and maintain. It improves code readability, reduces complexity, and enhances collaboration with other programmers.",
    "Correct. To make the code maintainable and reusable, Jade should focus on cleaning the code for readability. Clean code follows best practices and standards, making it easier to understand, modify, and maintain. It improves code readability, reduces complexity, and enhances collaboration with other programmers.",
    "Wrong. Re-running the program with different test cases is part of the testing process and not directly related to code maintainability or reusability.",
    "Wrong. Refactoring involves restructuring or optimizing the code to improve performance or efficiency. While performance optimization is important, the question specifically asks about making the code readable, maintainable, and reusable, which aligns with cleaning the code."
]

