[question-0]

prompt = "Jade is learning C programming and wants to create a program that calculates the area of a rectangle. She opens her code editor and starts writing a C program to perform the calculation. Jade inputs the length and width of the rectangle, and the program calculates and displays the area on the screen. Which component(s) of the computer system is/are responsible for executing the C program and display the result on the screen?"

answer = [0, 1, 2, 3]

distractors = ["CPU", "Main memory", "Input/Ouput device", "Operaing system"]

explainations = ["CPU is responsible for executing the C program written by Jade. It performs the calculations required to determine the area of the rectangle based on the provided length and width. The CPU consists of components such as the arithmetic logic unit (ALU) and the control unit, which work together to execute the program's instructions and perform the necessary calculations.", "It stores the C program code, as well as the data input (length and width of the rectangle) that Jade provides.", "The input device (such as a keyboard) is used by Jade to enter the length and width of the rectangle, which are inputs to the program. The output device (such as the screen) displays the calculated area as the result of the program.", "Although not directly mentioned in the scenario, the operating system plays a role in managing the execution of the program and coordinating the interaction between the CPU, main memory, and input/output devices."]


[question-1]

prompt = "In an analogy where a computer system is compared to the human body, which body parts can be associated with the following computer components"

answer = [0]

distractors = [
"""
CPU -- Brain
ALU -- Brain Cells
Control Unit -- Spinal Cord
Main Memory -- Short-term Memory
Input Devices -- Senses (Eyes, Ears, etc.)
Output Devices -- Hands, Vocal Cords
Operating System -- Nervous System
""",
"""
CPU -- Heart
ALU -- Blood Cells
Control Unit -- Nerves
Main Memory -- Long-term Memory
Input devices -- Hands, Feet
Output devices -- Eyes, Ears
Operating System -- Respiratory System
""",
"""
CPU -- Stomach
ALU -- Digestive Enzymes
Control Unit -- Skeletal System
Main Memory -- Long-term Memory
Input devices -- Lungs, Nose
Output devices -- Stomach, Intestines
Operating System -- Immune System
""",
"""
CPU -- Eyes
ALU -- Optic Nerve
Control Unit -- Brain
Main Memory -- Short-term Memory
Input devices -- Ears, Nose
Output devices -- Hands, Legs
Operating System -- Circulatory System
"""]

explainations = [
"""
CPU -- Brain: The CPU can be associated with the brain as it acts as the central processing unit of the computer, similar to how the brain controls and processes information in the human body.

ALU -- Brain Cells: The ALU, responsible for performing arithmetic and logical operations, can be compared to brain cells (neurons) that process and transmit information within the brain.

Control Unit -- Spinal Cord: The control unit, which manages the execution of instructions, can be associated with the spinal cord as it coordinates signals between the brain and the rest of the body.

Main Memory -- Short-term Memory: Main memory in a computer stores data and instructions temporarily during program execution, akin to short-term memory in humans that holds information temporarily for immediate use.

Input Devices -- Senses (Eyes, Ears, etc.): Input devices like the keyboard, mouse, and microphone can be associated with the senses (eyes, ears, etc.) in humans, as they provide input or sensory information to the computer system.

Output Devices -- Hands, vocal Cords: Output devices such as printers, speakers, and displays are comparable to hands and vocal cords, as they allow the computer system to express or output information through physical actions or sound.

Operating System -- Nervous System: The operating system manages and controls the overall operation of the computer system, analogous to the nervous system that coordinates and regulates various bodily functions.
""",
"""
CPU -- Heart: This option incorrectly associates the CPU with the heart. The heart's primary function is to pump blood and circulate it throughout the body, which does not align with the role of the CPU in a computer system.

ALU -- Blood Cells: This option incorrectly associates the ALU with blood cells. Blood cells are components of the circulatory system and do not perform arithmetic or logical operations like the ALU.

Control Unit -- Nerves: This option correctly associates the control unit with nerves, which is responsible for transmitting signals and coordinating communication between different parts of the body.

Main Memory -- Long-term Memory: This option incorrectly associates main memory with long-term memory. Main memory in a computer system refers to the storage that holds data and instructions temporarily during program execution.

Input Devices -- Hands, Feet: This option incorrectly associates input devices with hands and feet. Input devices such as a keyboard or mouse are more relevant to capturing user input, rather than physical body parts.

Output Devices -- Eyes, Ears: This option incorrectly associates output devices with eyes and ears. While eyes and ears are sensory organs that receive information, output devices in a computer system refer to devices that display or produce information for the user.

Operating System -- Respiratory System: This option incorrectly associates the operating system with the respiratory system. The respiratory system is responsible for the exchange of gases in the body, which does not align with the role of the operating system in managing computer resources.
""",
"""
CPU -- Stomach: This option incorrectly associates the CPU with the stomach. The stomach's primary function is to aid in digestion and break down food, which does not align with the role of the CPU in a computer system.

ALU -- Digestive Enzymes: This option incorrectly associates the ALU with digestive enzymes. Digestive enzymes are substances that aid in the breakdown of food molecules and do not perform arithmetic or logical operations like the ALU.

Control Unit -- Skeletal System: This option incorrectly associates the control unit with the skeletal system. The skeletal system provides support and protection for the body but does not fulfill the role of controlling the execution of instructions like the control unit.

Main Memory -- Long-term Memory: This option incorrectly associates main memory with long-term memory. Main memory in a computer system refers to the storage that holds data and instructions temporarily during program execution.

Input Devices -- Lungs, Nose: This option incorrectly associates input devices with the lungs and nose. While the lungs and nose are involved in the respiratory system and play a role in inputting oxygen and detecting smells, they are not the primary input devices for a computer system.

Output Devices -- Stomach, Intestines: This option incorrectly associates output devices with the stomach and intestines. The stomach and intestines are involved in the digestive system and do not align with the role of output devices in a computer system.

Operating System -- Immune System: This option incorrectly associates the operating system with the immune system. The immune system is responsible for defending the body against pathogens and maintaining overall health, which is not directly related to the functions of an operating system.
""",
"""
CPU -- Eyes: The CPU is the central processing unit of a computer, responsible for executing instructions and performing calculations. The eyes, on the other hand, are sensory organs that capture visual information.

ALU -- Optic Nerve: The ALU (Arithmetic Logic Unit) performs arithmetic and logical operations within the CPU. The optic nerve, however, is responsible for transmitting visual information from the eyes to the brain.

Control Unit -- Brain: The control unit manages and coordinates the execution of instructions within the CPU, similar to how the brain controls and coordinates various functions in the body.

Main Memory -- Short-term Memory: Main memory in a computer system refers to the temporary storage used for holding data and instructions during program execution, akin to short-term memory in the human brain that holds information temporarily for immediate use.

Input Devices -- Ears, Nose: While the ears and nose are indeed input sensory organs capturing auditory and olfactory information, other input devices such as keyboards and mice are commonly used in computer systems.

Output Devices -- Hands, Legs: Output devices in a computer system refer to devices that display or produce information for the user, such as monitors or printers. Hands and legs are part of the body's motor functions and are not directly related to outputting information from a computer system.

Operating System -- Circulatory System: The operating system manages and controls the computer's resources, whereas the circulatory system in the human body is responsible for circulating blood and delivering nutrients and oxygen to various parts of the body.
"""
]