[[questions]]

prompt = "Which of the following code snippets demonstrates good coding style, following the guidelines mentioned in the \"Bad coding style\" section of the handout?"

answer = [1]

distractors = [
"""
```
#include <stdio.h>
int main(void){printf("Hello World!\\n");return 0;}
```
""",
"""
```
#include <stdio.h>
int main(void) {
    printf("Hello World!\\n");
    return 0;
}
```
""",
"""
```
#include <stdio.h>
int main(void) {
    printf("Hello World!\\n");
return 0;}
```
""",
"""
```
#include <stdio.h>
int main(void) {
printf("Hello World!\\n");
return 0;}
```
"""
]

explainations = [
    "A) is not good coding style. Good coding style involves proper indentation, using new lines for readability, and placing opening and closing braces on separate lines. Option B adheres to these guidelines, making the code more readable and maintainable.",
    "B) is good coding style. Good coding style involves proper indentation, using new lines for readability, and placing opening and closing braces on separate lines. Option B adheres to these guidelines, making the code more readable and maintainable.",
    "C) is not good coding style. Good coding style involves proper indentation, using new lines for readability, and placing opening and closing braces on separate lines. Option B adheres to these guidelines, making the code more readable and maintainable.",
    "D) is not good coding style. Good coding style involves proper indentation, using new lines for readability, and placing opening and closing braces on separate lines. Option B adheres to these guidelines, making the code more readable and maintainable."
]

[[questions]]

prompt = """
Consider the code snippet below. How many errors are there in the code?
```
#include <stdio.h>

int main(void) {
    int num;
    
    printf("Enter a number: ");
    scanf("%d", num);
    
    printf("The number you entered is: %d\\n", &num);
    
    return 0
}
```
"""

answer = [3]

distractors = [
    "0",
    "1",
    "2",
    "3"
]

explainations = [
"""
There are 3 errors. 
Error 1: Missing ampersand before num in scanf:
The scanf function requires the address of the variable where the input should be stored. However, in this code, the ampersand (`&`) is missing before num in the scanf statement. To fix this error, you should use `scanf("%d", &num);`.

Error 2: Redundant ampersand before num in the second printf:
The printf function expects the value of the variable to be printed, not its address. In this code, there is a redundant ampersand (`&`) before num in the second printf statement. To fix this error, you should remove the ampersand and use `printf("The number you entered is: %d\\n", num);`.

Error 3: Missing semicolon at the end of the line:
At the end of the `return 0` line, there is a missing semicolon (`;`). In C, a semicolon is used to terminate a statement. To fix this error, you should add a semicolon at the end of the line, like this: `return 0;`.
""",
"""
There are 3 errors. 
Error 1: Missing ampersand before num in scanf:
The scanf function requires the address of the variable where the input should be stored. However, in this code, the ampersand (`&`) is missing before num in the scanf statement. To fix this error, you should use `scanf("%d", &num);`.

Error 2: Redundant ampersand before num in the second printf:
The printf function expects the value of the variable to be printed, not its address. In this code, there is a redundant ampersand (`&`) before num in the second printf statement. To fix this error, you should remove the ampersand and use `printf("The number you entered is: %d\\n", num);`.

Error 3: Missing semicolon at the end of the line:
At the end of the `return 0` line, there is a missing semicolon (`;`). In C, a semicolon is used to terminate a statement. To fix this error, you should add a semicolon at the end of the line, like this: `return 0;`.
""",
"""
There are 3 errors. 
Error 1: Missing ampersand before num in scanf:
The scanf function requires the address of the variable where the input should be stored. However, in this code, the ampersand (`&`) is missing before num in the scanf statement. To fix this error, you should use `scanf("%d", &num);`.

Error 2: Redundant ampersand before num in the second printf:
The printf function expects the value of the variable to be printed, not its address. In this code, there is a redundant ampersand (`&`) before num in the second printf statement. To fix this error, you should remove the ampersand and use `printf("The number you entered is: %d\\n", num);`.

Error 3: Missing semicolon at the end of the line:
At the end of the `return 0` line, there is a missing semicolon (`;`). In C, a semicolon is used to terminate a statement. To fix this error, you should add a semicolon at the end of the line, like this: `return 0;`.
""",
"""
There are 3 errors. 
Error 1: Missing ampersand before num in scanf:
The scanf function requires the address of the variable where the input should be stored. However, in this code, the ampersand (`&`) is missing before num in the scanf statement. To fix this error, you should use `scanf("%d", &num);`.

Error 2: Redundant ampersand before num in the second printf:
The printf function expects the value of the variable to be printed, not its address. In this code, there is a redundant ampersand (`&`) before num in the second printf statement. To fix this error, you should remove the ampersand and use `printf("The number you entered is: %d\\n", num);`.

Error 3: Missing semicolon at the end of the line:
At the end of the `return 0` line, there is a missing semicolon (`;`). In C, a semicolon is used to terminate a statement. To fix this error, you should add a semicolon at the end of the line, like this: `return 0;`.
"""
]

[[questions]]

prompt = "Consider the code snippet below. How can you print the '2%d\\tab\\2%d' using printf?"

answer = [0]

distractors = [
"""
```
int num = 2;
printf("%d%%d\\\\tab\\\\%d%%d\\n", num, num);
```
""",
"""
```
int num = 2;
printf("%d\\%d\\\\tab\\\\%d\\%d\\n", num, num);
```
""",
"""
```
int num = 2;
printf("%d%%d\\\\tab\\\\%d%%d\\n", num);
```
""",
"""
```
int num = 2;
printf("%d%d\\\\tab\\\\%d%d\\n", num);
```
"""
]

explainations = [
    "A) is correct. For \\'%\\' to be printed, you need to use \\'%%\\'; for \\'\\\\' to be printed you need to use \\'\\\\\\\\\\'. There are two decimal numbers to be printed, so you need to use two \\'%d\\'s and follow the format specifier with the two variables separately, even though they are the same.",
    "B) is incorrect. It should use \\'%%\\' to print \\'%\\'. Here the first two \\'%d\\'s will be replaced by the two numbers, and the last two \\'%d\\'s will be replaced by garbage values.",
    "C) is incorrect. It should use two \\'%d\\'s to print the two numbers. The last \\'%d\\' will be replaced by a garbage value.",
    "D) is incorrect. It should use \\'%%\\' to print \\'%\\'. Here the first \\'%d\\' will be replaced by the number, and the rest will be replaced by garbage values."
]
