[[questions]]

prompt = "Which of is following code can determine the median of `x`, `y`, and `z` (Assume they are not identical)?"

answer = [0, 1, 2, 3]

distractors = [
'''
```
if (x < y) {
    if (x > z) {
        printf("median is %d", x);
    } else if (y < z) {
        printf("median is %d", y);
    } else {
        printf("median is %d", z);
    }
} else {
    if (x < z) {
        printf("median is %d", x);
    } else if (y > z) {
        printf("median is %d", y);
    } else {
        printf("median is %d", z);
    }
}
```
''',
'''
```
if (x < y && x < z) {
    if (y < z) {
        printf("median is %d", y);
    } else {
        printf("median is %d", z);
    }
} else if (x > y) {
    if (x < z) {
        printf("median is %d", x);
    } else if (y > z) {
        printf("median is %d", y);
    } else {
        printf("median is %d", z);
    }
} else {
    if (x < y) {
        printf("median is %d", x);
    } else if (y < z) {
        printf("median is %d", z);
    } else {
        printf("median is %d", y);
    }
}
```
''',
'''
```
if (((x < y) && (x > z)) || ((x < z) && (x > y))) {
    printf("median is %d", x);
} else if (((y < x) && (y > z)) || ((y < z) && (y > x))) {
    printf("median is %d", y);
} else {
    printf("median is %d", z);
}
```
''',
'''
```
if (((x < y) || (x < z)) && ((x > y) || (x > z))) {
    printf("median is %d", x);
} else if (((y < x) || (y < z)) && ((y > x) || (y > z))) {
    printf("median is %d", y);
} else {
    printf("median is %d", z);
}
```
'''
]

explainations = [
    "A is correct. It first compares `x` and `y`, then uses the nested `if` to build the condition of each variable being the median.",
    "B is correct. It is similar to A, but extracts the first nested `if` in the first branch of the outer `if`.",
    "C is correct. It is a more readable version of A and B.",
    "D is correct. It is the same as C."
]

[[questions]]

prompt = "Which of the following code can output `Odd` if `x` is odd and `Mul-6` if `x` is divisible by 6?"

answer = [1, 3]

distractors = [
'''
```
if (x % 2 == 0)
    if (x % 3 == 0)
        printf("Mul-6");
else
    printf("Odd");
```
''',
'''
```
if (x % 2 == 0 && x % 3 == 0)
    printf("Mul-6");
else if (x % 2 != 0)
    printf("Odd");
```
''',
'''
```
if (x % 2 == 0 && x % 3 == 0)
    printf("Mul-6");
else if (x % 3 == 0)
    printf("Odd");
```
''',
'''
```
if (x % 2 == 0) {
    if (x % 3 == 0)
        printf("Mul-6");
} else
    printf("Odd");
```
'''
]

explainations = [
    "A is incorrect. The dangling `else` is attached to the inner `if`.",
    "B is correct. It first checks if `x` is divisible by 6, then checks if `x` is odd.",
    "C is incorrect. It first checks if `x` is divisible by 6, then it checks if `x` is the odd which is also divisible by 3, but not all odd numbers.",
    "D is correct. It first checks if `x` is even or odd, then checks if `x` is divisible by 3 when it is even."
]

