[[questions]]

prompt = '''The following code tries to count the number of vowels in a string. 
```
#include <stdio.h>
#include <string.h>

int countVowels(char *);

int main(void) {
  printf("Number of vowels: %d", countVowels("Hello world!"));
  return 0;
}

int countVowels(char *s) {
  if (*s == '\0') {
    return 0;
  } else if (*s == 'a' || *s == 'e' || *s == 'i' || *s == 'o' || *s == 'u') {
    return -----------;
  } else {
    return -----------;
  }
}
```
How would you complete line 15 and 17?
'''

answer = [2]

distractors = [
'''
Line 15, `countVowels(s)`;
Line 17, `countVowels(s)`;
''',
'''
Line 15, `countVowels(s + 1)`;
Line 17, `countVowels(s + 1)`;
''',
'''
Line 15, `1 + countVowels(s + 1)`;
Line 17, `countVowels(s + 1)`;
''',
'''
Line 15, `countVowels(s + 1)`;
Line 17, `countVowels(s)`;
'''
]

explainations = [
'''
A is incorrect. 
As the next time, we call the function, we look at the string `s`, not a smaller version of it.
''',
'''
B is incorrect. 
Calling `countVowels` on `s + 1` does reduce the size of the problem, however, if we encounter a vowel at `s[0]`, we need to add 1 to the return value.
''',
'''
C is correct. 
We add one to the return value when a vowel is observed, and add nothing other wise.
''',
'''
D is incorrect. 
We need to call `countVowels` on a smaller string by advancing the pointer `s` by one place. 
'''
]
