[[questions]]

prompt = "Which of the following code can print the odd number from 1 to 10?"

answer = [0, 1, 2, 3]

distractors = [
'''
```
int i = 1;
while (i <= 5) {
    printf("%d ", i * 2 - 1);
    i++;
}
```
''',
'''
```
int i = 1;
do {
    printf("%d ", i);
    i += 2;
} while (i < 10);
```
''',
'''
```
int i = 10;
do {
    printf("%d ", 11 - i);
    i -= 2;
} while (i < 10 && i > 1);
```
''',
'''
```
bool start = false;
int i = 0;
do {
    i++;
    if (i >= 1 && i < 10) {
        start = true;
    } else {
        start = false;
    }
    if (i % 2 == 1) {
        printf("%d ", i);
    }
} while (start);
```
'''
]

explainations = [
    "A is correct. The loop will print 1 3 5 7 9.",
    "B is correct. This is a basic do-while loop usage.",
    "C is correct. Similar to B, but use a inverse formular to print the odd number.",
    "D is correct. Notice that the do-while will always run at least once, so in in the first iteration, the `start` will be set to true, so the loop will run until `i` is 10 where `start` will be set to false."
]