[[questions]]

prompt = '''
Jade writes a program to print the following figure (input is 3):
```
11111
12221
12321
12221
11111
```
The figure is a lots of squares. Each square is made of numbers. The numbers in the square are the same. The numbers in the square are from 1 to the half of the width of the square. The width of the square is an odd number. The width of the square is 5 in the example above.

Here is the code Jade writes:
```
#include <stdio.h>

int main() {
    int n = 7;
    for (int row = 1; row <= n; row++) {
        for (int col = 1; col <= n; col++) {
            int temp_row = row;
            if (row >= n / 2 + 1) {
                temp_row = n - row + 1;
            }
            int num = temp_row;
            if (col < temp_row - 1) {
                num = col;
            }
            if (col > n - temp_row + 1) {
                num = n - col + 1;
            }
            printf("%d", num);
            printf("\n");
        }
    }
    return 0;
}
```
How many errors are there in the code?
'''

answer = [1]

distractors = [
    "1",
    "2",
    "3",
    "4"
]

explainations = [
'''
A is incorrect. There are 2 errors in the code.
Error 1:
The 11th line, condition `col < temp_row - 1` is incorrect. When `n` is 5, `col` is 1 and `row` is 2, this condition will be true. The output will be like:
```
11111
22221
13321
22221
11111
```
The correct version is `col < temp_row`.

Error 2:
The 18th line, print new line should be outside the inner loop.
''',
'''
B is correct. There are 2 errors in the code.
Error 1:
The 11th line, condition `col < temp_row - 1` is incorrect. When `n` is 5, `col` is 1 and `row` is 2, this condition will be true. The output will be like:
```
11111
22221
13321
22221
11111
```
The correct version is `col < temp_row`.

Error 2:
The 18th line, print new line should be outside the inner loop.
''',
'''
C is incorrect. There are 2 errors in the code.
Error 1:
The 11th line, condition `col < temp_row - 1` is incorrect. When `n` is 5, `col` is 1 and `row` is 2, this condition will be true. The output will be like:
```
11111
22221
13321
22221
11111
```
The correct version is `col < temp_row`.

Error 2:
The 18th line, print new line should be outside the inner loop.
''',
'''
D is incorrect. There are 2 errors in the code.
Error 1:
The 11th line, condition `col < temp_row - 1` is incorrect. When `n` is 5, `col` is 1 and `row` is 2, this condition will be true. The output will be like:
```
11111
22221
13321
22221
11111
```
The correct version is `col < temp_row`.

Error 2:
The 18th line, print new line should be outside the inner loop.
'''
]